### ISSUE TITLE
Move under custom namespace

### ISSUE THREAD

**Issue by vinkla** [hassankhan/instagram-sdk#16]
I think it would be better if we moved `Instagram\Instagram` to `Hassankhan\Instagram\Instagram`. 

In this way there will never be any conflicts when working with this package.

**Comment by hassankhan** [comment]
I'm planning on moving this repo (and others) to an organisation - would you be interested in being a contributor?

**Comment by vinkla** [comment]
Yeah, definitely!

**Comment by vinkla** [comment]
Then I'll wait with my Laravel integration until we've moved it.

**Comment by vinkla** [comment]
What is the name of the org?

**Comment by hassankhan** [comment]
https://github.com/larabros

I just sent you an invite

**Comment by vinkla** [comment]
Thanks!

Just bare in mind that you will loose all downloads if you change the package name.

**Comment by hassankhan** [comment]
Not too worried - there's less than 10 downloads I think :)

**Comment by vinkla** [comment]
Yeah, this repo shouldn't be a problem but if you're going to move other packages.

**Comment by hassankhan** [comment]
Done! Only took all evening :smile:

**Comment by vinkla** [comment]
:+1:
