### ISSUE TITLE
Make sure Scrutinizer-CI gets updates

### ISSUE THREAD

**Issue by hassankhan** [hassankhan/instagram-sdk#19]
## Expected Behavior

Scrutinizer should work.
## Current Behavior

Scrutinizer does not work.
## Possible Solution

Scrutinizer should sort it out.
## Steps to Reproduce (for bugs)
1. Open `README.md`
2. Weep
3. ???
4. Profit
## Context

Personally, I'm devastated. Ever since that gorgeous green badge turned lifeless and grey, my world has become dull and sullen, and I no longer look forward to anything at all, hapless and hopeless.

![You are tearing me apart Lisa!](http://i.imgur.com/c3yjhwL.gif)

**Comment by vinkla** [comment]
![happy](https://i.giphy.com/3oxRmeLK7bjcq0CCCA.gif)

**Comment by hassankhan** [comment]
Unfortunately I had to delete and recreate the repo, so all the history is gone

![](https://media.giphy.com/media/jDm21PV7ICkdq/giphy.gif)
