### ISSUE TITLE
Rename Client class to Instagram

### ISSUE THREAD

**Issue by vinkla** [hassankhan/instagram-sdk#22]
The title is quite explanatory. IMO it will be a lot easier to read. What do you think? 

Before:

``` php
use Larabros\Elogram\Client;

$client = new Client($clientId, $clientSecret, $accessToken);

$response = $client->media()->search(51.503349, -0.252271);
```

After:

``` php
use Larabros\Elogram\Instagram;

$instagram = new Instagram($clientId, $clientSecret, $accessToken);

$response = $instagram->media()->search(51.503349, -0.252271);
```

**Comment by hassankhan** [comment]
I changed it the other way round on purpose - `Client` better describes what the class is doing and anyone importing can always do `use Larabros\Elogram\Client as Instagram`. Is that ok?

**Comment by vinkla** [comment]
Yeah, that is true. Just thought it could be more readable. I dunno. Just an idea.
