### ISSUE TITLE
Error "Alias (provider) is not being managed by the container"

### ISSUE THREAD

**Issue by melnikoved** [hassankhan/instagram-sdk#31]
## Current Behavior

I am using this repo first once. I have Symfony3 application. And after "$client->getLoginUrl()" it is shown:

> Uncaught PHP Exception League\Container\Exception\NotFoundException: "Alias (provider) is not being managed by the container" at /var/www/activity/vendor/league/container/src/Container.php line 98

**Comment by hassankhan** [comment]
Could you try again with the latest version?

**Comment by hassankhan** [comment]
Any luck?

**Comment by inanolcer** [comment]
Hi, 
I am developing an application ısing vinkla/instagram wrapper for elogram on laravel 5.2.27
Still getting this error, also investigated league/container  elogram/CoreServiceProvider classes but could not achieve a solution.
@hassankhan Any clue would be great we want to fix this issue, and open for collaboration.

btw : Elogram login system works fine without a wrapper class.

**Comment by hassankhan** [comment]
We're working on a solution to fix the wrapper package, but in the meantime can you use it directly? Closing this issue for now, if any new unexpected issues arise, I'm sure someone can open a new issue 😄
