### ISSUE TITLE
Problems with "public_content" scope

### ISSUE THREAD

**Issue by andeersg** [hassankhan/instagram-sdk#35]
Hi, I'm trying to use the `users->find()` method to look up a username. I have a sandbox app and a 
access token with the public_content permission.

"Self" works, but no other usernames.
## Expected Behavior

When I try to lookup "instagram" I expect to get a result.
## Current Behavior

I get null back. 
## Steps to Reproduce (for bugs)

My testing code:

```
$instagram = new Client($config->get('instagram.key'), $config->get('instagram.secret'), $this->token, '');
$response = $instagram->users()->find($username);
```
## Your Environment
- Environment name and version: PHP 5.6 on Apache/2.2.31 (Unix) 
- Operating System and version: OS X El Capitan

**Comment by hassankhan** [comment]
Looks like you didn't set the correct scope when you requested the access token.

You'll have to reauthorize the user while setting the additional scopes (using `getLoginUrl()`)

**Comment by andeersg** [comment]
Thank you for your quick response.

I have tested the `getLoginUrl()` and revoked the application to authenticate again. And I'm still seeing the same problem. Under my account the app is listed with the correct permissions.

The app is still in Sandbox-mode if that can affect this somehow?

**Comment by hassankhan** [comment]
How did you request the extra scopes? Could you show me a code example? Thanks

**Comment by andeersg** [comment]
I generated a link manually: https://api.instagram.com/oauth/authorize/?client_id=&redirect_uri=&response_type=code&scope=public_content

But I found on StackOverflow that while the app is in sandbox-mode you can only fetch data for approved users: http://stackoverflow.com/questions/33886881/instagram-api-returns-empty-data-for-sandbox-users-when-trying-to-access-liked-c

So when I added another user I could look it up.

**Comment by hassankhan** [comment]
Ahh right, good to close the issue then?

**Comment by andeersg** [comment]
Yes, no problems with your library :)
