### ISSUE TITLE
Error when access any endpoint 

### ISSUE THREAD

**Issue by abada** [hassankhan/instagram-sdk#38]
```
FatalThrowableError in AuthMiddleware.php line 36:
Fatal error: Call to a member function getToken() on string
```

It can not found `access_token` config

https://github.com/larabros/elogram/blob/d65050410357ea9abca1cb845194c8059608b1c7/src/Http/Middleware/AuthMiddleware.php#L36

**Comment by hassankhan** [comment]
Have you set an access token correctly?

**Comment by abada** [comment]
There is no accses  token :(  , first user must approve instagram app and redirect to my website and then access his account 
So in first time access token is NULL

**Comment by hassankhan** [comment]
You can't make requests to the API without getting an access token, it just doesn't work that way. Please read the both the [Instagram API documentation](https://www.instagram.com/developer/) and [Elogram documentation](http://elogram.readthedocs.io/en/stable/overview.html) first.
